# Generated by Django 3.2.6 on 2021-08-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(choices=[('Life', (('Daily', 'Daily'), ('RelationShip', 'RelationShip'), ('Family', 'Family'), ('Pets', 'Pets'), ('Hobby', 'Hobby'), ('Photography', 'Photography'), ('Cook', 'Cook'), ('Car', 'Car'), ('Interior', 'Interior'), ('Fashion/Beauty', 'Fashion/Beauty'), ('Health', 'Health'))), ('Travel/Restaurants', (('Domestic', 'Domestic'), ('Oversea', 'Oversea'), ('Camping/Hiking', 'Camping/Hiking'), ('Restaurants', 'Restaurants'), ('Cafe', 'Cafe'))), ('Entertainment', (('Tv', 'Tv'), ('Star', 'Star'), ('Movie', 'Movie'), ('Music', 'Music'), ('Book', 'Book'), ('Animation', 'Animation'), ('Exhibition', 'Exhibition'), ('Show', 'Show'), ('Craft', 'Craft'))), ('IT', (('IT Internet', 'IT Internet'), ('Mobile', 'Mobile'), ('Game', 'Game'), ('Science', 'Science'), ('IT Product', 'IT Product'))), ('Sports', (('Sports', 'Sports'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Golf', 'Golf'))), ('Current', (('Government', 'Government'), ('Society', 'Society'), ('Education', 'Education'), ('International', 'International'), ('Business', 'Business'), ('Economy', 'Economy'), ('Job', 'Job'))), ('Event', (('Event', 'Event'),))], max_length=40),
        ),
    ]
