# Generated by Django 3.2.6 on 2021-08-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
