# Generated by Django 3.2.6 on 2021-08-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='myuser',
        ),
    ]
