# Generated by Django 3.2.6 on 2021-08-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_myuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table=None,
        ),
    ]
